// v2-app/src/lib/components/list/ListItem.svelte
<script lang="ts">
	import { getRepository } from '$lib/config';
	import { userStore } from '$lib/stores';
	import type { ListItem } from '$lib/contracts/list.contracts';
	import VerificationButtons from './VerificationButtons.svelte';
	import ConsensusMeter from './ConsensusMeter.svelte';
	import { Badge } from '$lib/components/common';

	interface Props {
		item: ListItem;
		listId: string;
		onUpdate?: () => void;
		onDelete?: (itemId: string) => void;
	}

	let { item, listId, onUpdate, onDelete }: Props = $props();

	const listRepo = getRepository('list');
	let editing = $state(false);
	let editText = $state(item.text);
	let showCorrectionsList = $state(false);
	let editInput: HTMLInputElement;

	const bgColor = $derived(
		item.verificationStatus === 'accurate'
			? 'bg-green-900/20 border-green-700'
			: item.verificationStatus === 'inaccurate'
				? 'bg-red-900/20 border-red-700'
				: 'bg-gray-800 border-gray-700'
	);

	const statusBadgeVariant = $derived(
		item.verificationStatus === 'accurate'
			? 'success'
			: item.verificationStatus === 'inaccurate'
				? 'error'
				: 'neutral'
	) as 'success' | 'error' | 'neutral';

	function startEditing() {
		editing = true;
		setTimeout(() => editInput?.focus(), 0);
	}

	async function handleEdit() {
		if (editText.trim() === item.text) {
			editing = false;
			return;
		}

		const response = await listRepo.updateListItem({
			itemId: item.id,
			text: editText.trim()
		});

		if ('item' in response) {
			editing = false;
			onUpdate?.();
		}
	}

	async function handleVerify(isAccurate: boolean, correctionText?: string) {
		if (!userStore.currentUser) return;

		const response = await listRepo.verifyListItem({
			itemId: item.id,
			userId: userStore.currentUser.id,
			userName: userStore.displayName,
			isAccurate,
			correctionText
		});

		if ('verification' in response) {
			onUpdate?.();
		}
	}

	async function handleDelete() {
		if (!confirm('Delete this item?')) return;

		const response = await listRepo.deleteListItem({
			itemId: item.id
		});

		if ('success' in response && response.success) {
			onDelete?.(item.id);
		}
	}
</script>

<div class="p-4 rounded-lg border-2 transition-colors {bgColor}">
	<div class="flex items-start justify-between gap-3">
		<!-- Content -->
		<div class="flex-1">
			<div class="flex items-center gap-2 mb-2">
				{#if editing}
					<input
						type="text"
						bind:this={editInput}
						bind:value={editText}
						onblur={handleEdit}
						onkeydown={(e) => e.key === 'Enter' && handleEdit()}
						class="flex-1 px-3 py-1 bg-gray-900 border border-purple-600 rounded text-white text-sm"
					/>
				{:else}
					<button
						type="button"
						onclick={startEditing}
						class="text-white flex-1 text-left cursor-pointer hover:opacity-80 transition-opacity py-1"
						title="Double-click to edit"
					>
						{item.text}
					</button>
				{/if}

				{#if item.verificationStatus !== 'neutral'}
					<Badge text={item.verificationStatus} variant={statusBadgeVariant} />
				{/if}
			</div>

			<!-- Consensus Meter -->
			{#if item.verificationCount.total > 0}
				<div class="mt-3 mb-3">
					<ConsensusMeter
						accurateCount={item.verificationCount.accurate}
						inaccurateCount={item.verificationCount.inaccurate}
						totalCount={item.verificationCount.total}
					/>
				</div>
			{/if}

			<!-- Corrections List -->
			{#if item.corrections.length > 0}
				<div class="mt-3">
					<button
						onclick={() => (showCorrectionsList = !showCorrectionsList)}
						class="text-xs text-blue-400 hover:text-blue-300 transition-colors"
					>
						{showCorrectionsList ? '▼' : '▶'} {item.corrections.length} correction
						{item.corrections.length === 1 ? 'suggestion' : 'suggestions'}
					</button>

					{#if showCorrectionsList}
						<div class="mt-2 pl-3 border-l-2 border-gray-600 space-y-2">
							{#each item.corrections as correction (correction.userId)}
								<div class="bg-gray-900/50 p-2 rounded text-xs">
									<p class="text-gray-300 font-medium">{correction.userName}:</p>
									<p class="text-gray-400 italic">{correction.correctionText}</p>
								</div>
							{/each}
						</div>
					{/if}
				</div>
			{/if}
		</div>

		<!-- Actions -->
		<div class="flex flex-col gap-2">
			<VerificationButtons onVerify={handleVerify} />
			<button
				onclick={handleDelete}
				class="px-2 py-1 text-xs bg-red-600 hover:bg-red-700 text-white rounded transition-colors"
			>
				Delete
			</button>
		</div>
	</div>
</div>

// components/lists/list-item.tsx
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { CheckCircle2, XCircle, Edit2, Trash2, MessageSquare } from 'lucide-react'
import { useListItemVerifications } from '@/hooks/use-collaborative-lists'
import { type ListItem } from '@/lib/types'

interface ListItemComponentProps {
  item: ListItem
  index: number
  listType: 'bullet' | 'numbered'
  userId: string
  userName: string
  isCreator: boolean
  onUpdate: (itemId: string, text: string) => void
  onDelete: (itemId: string) => void
}

export default function ListItemComponent({
  item,
  index,
  listType,
  userId,
  userName,
  isCreator,
  onUpdate,
  onDelete,
}: ListItemComponentProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [editText, setEditText] = useState(item.text)
  const [showCorrectionField, setShowCorrectionField] = useState(false)
  const [correctionText, setCorrectionText] = useState('')
  
  const { verifications, myVerification, submitVerification } = useListItemVerifications(
    item.id,
    userId,
    userName
  )

  const handleSave = () => {
    if (editText.trim() && editText !== item.text) {
      onUpdate(item.id, editText)
    }
    setIsEditing(false)
  }

  const handleVerify = async (isAccurate: boolean) => {
    if (!isAccurate && !correctionText.trim() && !myVerification) {
      setShowCorrectionField(true)
      return
    }

    await submitVerification(isAccurate, correctionText.trim() || undefined)
    if (!isAccurate) {
      setShowCorrectionField(false)
      setCorrectionText('')
    }
  }

  // Calculate consensus
  const totalVerifications = verifications.length
  const accurateCount = verifications.filter(v => v.is_accurate).length
  const inaccurateCount = totalVerifications - accurateCount
  const consensusPercentage = totalVerifications > 0 ? (accurateCount / totalVerifications) * 100 : 0

  // Get consensus color
  const getConsensusColor = () => {
    if (totalVerifications === 0) return 'bg-gray-200'
    if (consensusPercentage >= 80) return 'bg-green-500'
    if (consensusPercentage >= 50) return 'bg-yellow-500'
    return 'bg-red-500'
  }

  const prefix = listType === 'numbered' ? `${index + 1}.` : '•'

  return (
    <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 mb-3 border-l-4" style={{ borderLeftColor: myVerification?.is_accurate ? '#22c55e' : myVerification?.is_accurate === false ? '#ef4444' : '#d1d5db' }}>
      <div className="flex items-start gap-3">
        <span className="font-bold text-gray-600 dark:text-gray-300 mt-1">{prefix}</span>
        
        <div className="flex-1">
          {isEditing ? (
            <div className="space-y-2">
              <Input
                value={editText}
                onChange={(e) => setEditText(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault()
                    handleSave()
                  }
                  if (e.key === 'Escape') {
                    setIsEditing(false)
                    setEditText(item.text)
                  }
                }}
                autoFocus
              />
              <div className="flex gap-2">
                <Button size="sm" onClick={handleSave}>Save</Button>
                <Button size="sm" variant="outline" onClick={() => {
                  setIsEditing(false)
                  setEditText(item.text)
                }}>Cancel</Button>
              </div>
            </div>
          ) : (
            <>
              <p className="text-gray-800 dark:text-gray-200">{item.text}</p>
              
              {/* Consensus Bar */}
              {totalVerifications > 0 && (
                <div className="mt-3">
                  <div className="flex items-center gap-2 text-xs text-gray-600 dark:text-gray-400 mb-1">
                    <span>{accurateCount} ✓</span>
                    <span>{inaccurateCount} ✗</span>
                    <span className="ml-auto">{Math.round(consensusPercentage)}% consensus</span>
                  </div>
                  <div className="h-2 bg-gray-200 dark:bg-gray-600 rounded-full overflow-hidden">
                    <div
                      className={`h-full transition-all duration-300 ${getConsensusColor()}`}
                      style={{ width: `${consensusPercentage}%` }}
                    />
                  </div>
                </div>
              )}

              {/* Verifications from others */}
              {verifications.length > 0 && (
                <div className="mt-3 space-y-2">
                  {verifications.map(v => (
                    <div key={v.id} className="text-xs bg-white dark:bg-gray-800 rounded p-2 flex items-start gap-2">
                      {v.is_accurate ? (
                        <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" />
                      ) : (
                        <XCircle className="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5" />
                      )}
                      <div className="flex-1">
                        <span className="font-medium">{v.user_name}</span>
                        {v.correction_text && (
                          <p className="text-gray-600 dark:text-gray-400 mt-1">
                            <MessageSquare className="w-3 h-3 inline mr-1" />
                            {v.correction_text}
                          </p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Verification Actions (for non-creators) */}
              {!isCreator && (
                <div className="mt-3 space-y-2">
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant={myVerification?.is_accurate === true ? 'default' : 'outline'}
                      onClick={() => handleVerify(true)}
                      className="flex-1"
                    >
                      <CheckCircle2 className="w-4 h-4 mr-1" />
                      Accurate
                    </Button>
                    <Button
                      size="sm"
                      variant={myVerification?.is_accurate === false ? 'destructive' : 'outline'}
                      onClick={() => handleVerify(false)}
                      className="flex-1"
                    >
                      <XCircle className="w-4 h-4 mr-1" />
                      Inaccurate
                    </Button>
                  </div>

                  {showCorrectionField && (
                    <div className="space-y-2">
                      <Input
                        placeholder="Suggest a correction..."
                        value={correctionText}
                        onChange={(e) => setCorrectionText(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter' && !e.shiftKey) {
                            e.preventDefault()
                            handleVerify(false)
                          }
                        }}
                      />
                      <Button
                        size="sm"
                        variant="destructive"
                        onClick={() => handleVerify(false)}
                        disabled={!correctionText.trim()}
                      >
                        Submit Correction
                      </Button>
                    </div>
                  )}
                </div>
              )}

              {/* Edit/Delete Actions (for creator) */}
              {isCreator && (
                <div className="flex gap-2 mt-3">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => setIsEditing(true)}
                  >
                    <Edit2 className="w-3 h-3 mr-1" />
                    Edit
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => onDelete(item.id)}
                  >
                    <Trash2 className="w-3 h-3 mr-1" />
                    Delete
                  </Button>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  )
}
